package ntu.csie.oop13spring;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JPanel;

public class MainWindow extends javax.swing.JFrame {

    public MainWindow(String title) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        setTitle(title);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width/2-getSize().width/2, dim.height/2-getSize().height/2);
        getContentPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Panel = new javax.swing.JPanel();
        Stat_Panel = new javax.swing.JPanel();
        P1_Stat_Panel = new javax.swing.JPanel();
        P2_Stat_Panel = new javax.swing.JPanel();
        P3_Stat_Panel = new javax.swing.JPanel();
        P4_Stat_Panel = new javax.swing.JPanel();
        P5_Stat_Panel = new javax.swing.JPanel();
        P6_Stat_Panel = new javax.swing.JPanel();
        P7_Stat_Panel = new javax.swing.JPanel();
        P8_Stat_Panel = new javax.swing.JPanel();
        Combat_Panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        Main_Panel.setPreferredSize(new java.awt.Dimension(800, 551));
        Main_Panel.setLayout(null);

        Stat_Panel.setBackground(new java.awt.Color(153, 153, 255));
        Stat_Panel.setPreferredSize(new java.awt.Dimension(800, 100));
        Stat_Panel.setLayout(new java.awt.GridLayout(1, 8));

        P1_Stat_Panel.setBackground(Stat_Panel.getBackground());
        P1_Stat_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout P1_Stat_PanelLayout = new javax.swing.GroupLayout(P1_Stat_Panel);
        P1_Stat_Panel.setLayout(P1_Stat_PanelLayout);
        P1_Stat_PanelLayout.setHorizontalGroup(
            P1_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        P1_Stat_PanelLayout.setVerticalGroup(
            P1_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        Stat_Panel.add(P1_Stat_Panel);

        P2_Stat_Panel.setBackground(Stat_Panel.getBackground());
        P2_Stat_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout P2_Stat_PanelLayout = new javax.swing.GroupLayout(P2_Stat_Panel);
        P2_Stat_Panel.setLayout(P2_Stat_PanelLayout);
        P2_Stat_PanelLayout.setHorizontalGroup(
            P2_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        P2_Stat_PanelLayout.setVerticalGroup(
            P2_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        Stat_Panel.add(P2_Stat_Panel);

        P3_Stat_Panel.setBackground(Stat_Panel.getBackground());
        P3_Stat_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout P3_Stat_PanelLayout = new javax.swing.GroupLayout(P3_Stat_Panel);
        P3_Stat_Panel.setLayout(P3_Stat_PanelLayout);
        P3_Stat_PanelLayout.setHorizontalGroup(
            P3_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        P3_Stat_PanelLayout.setVerticalGroup(
            P3_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        Stat_Panel.add(P3_Stat_Panel);

        P4_Stat_Panel.setBackground(Stat_Panel.getBackground());
        P4_Stat_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout P4_Stat_PanelLayout = new javax.swing.GroupLayout(P4_Stat_Panel);
        P4_Stat_Panel.setLayout(P4_Stat_PanelLayout);
        P4_Stat_PanelLayout.setHorizontalGroup(
            P4_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        P4_Stat_PanelLayout.setVerticalGroup(
            P4_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        Stat_Panel.add(P4_Stat_Panel);

        P5_Stat_Panel.setBackground(Stat_Panel.getBackground());
        P5_Stat_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout P5_Stat_PanelLayout = new javax.swing.GroupLayout(P5_Stat_Panel);
        P5_Stat_Panel.setLayout(P5_Stat_PanelLayout);
        P5_Stat_PanelLayout.setHorizontalGroup(
            P5_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        P5_Stat_PanelLayout.setVerticalGroup(
            P5_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        Stat_Panel.add(P5_Stat_Panel);

        P6_Stat_Panel.setBackground(Stat_Panel.getBackground());
        P6_Stat_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout P6_Stat_PanelLayout = new javax.swing.GroupLayout(P6_Stat_Panel);
        P6_Stat_Panel.setLayout(P6_Stat_PanelLayout);
        P6_Stat_PanelLayout.setHorizontalGroup(
            P6_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        P6_Stat_PanelLayout.setVerticalGroup(
            P6_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        Stat_Panel.add(P6_Stat_Panel);

        P7_Stat_Panel.setBackground(Stat_Panel.getBackground());
        P7_Stat_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout P7_Stat_PanelLayout = new javax.swing.GroupLayout(P7_Stat_Panel);
        P7_Stat_Panel.setLayout(P7_Stat_PanelLayout);
        P7_Stat_PanelLayout.setHorizontalGroup(
            P7_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        P7_Stat_PanelLayout.setVerticalGroup(
            P7_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        Stat_Panel.add(P7_Stat_Panel);

        P8_Stat_Panel.setBackground(Stat_Panel.getBackground());
        P8_Stat_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout P8_Stat_PanelLayout = new javax.swing.GroupLayout(P8_Stat_Panel);
        P8_Stat_Panel.setLayout(P8_Stat_PanelLayout);
        P8_Stat_PanelLayout.setHorizontalGroup(
            P8_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        P8_Stat_PanelLayout.setVerticalGroup(
            P8_Stat_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
        );

        Stat_Panel.add(P8_Stat_Panel);

        Main_Panel.add(Stat_Panel);
        Stat_Panel.setBounds(0, 1, 1000, 90);

        Combat_Panel.setBackground(new java.awt.Color(0, 204, 204));
        Main_Panel.add(Combat_Panel);
        Combat_Panel.setBounds(0, 90, 1000, 460);

        getContentPane().add(Main_Panel, java.awt.BorderLayout.CENTER);
        Main_Panel.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Credit");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Exit");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected JPanel getStatPanels(int i){
        if(i==1) return P1_Stat_Panel;
        else if(i==2) return P2_Stat_Panel;
        else if(i==3) return P3_Stat_Panel;
        else if(i==4) return P4_Stat_Panel;
        else if(i==5) return P5_Stat_Panel;
        else if(i==6) return P6_Stat_Panel;
        else if(i==7) return P7_Stat_Panel;
        else if(i==8) return P8_Stat_Panel;
        return null;
    }
    
    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        AlertFrame frame = new AlertFrame("thank you for playing POOArena!!");
        frame.setVisible(true);        
        dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new AlertFrame("Written by B99902006 王柏軒").setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel Combat_Panel;
    protected javax.swing.JPanel Main_Panel;
    protected javax.swing.JPanel P1_Stat_Panel;
    protected javax.swing.JPanel P2_Stat_Panel;
    protected javax.swing.JPanel P3_Stat_Panel;
    protected javax.swing.JPanel P4_Stat_Panel;
    protected javax.swing.JPanel P5_Stat_Panel;
    protected javax.swing.JPanel P6_Stat_Panel;
    protected javax.swing.JPanel P7_Stat_Panel;
    protected javax.swing.JPanel P8_Stat_Panel;
    private javax.swing.JPanel Stat_Panel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
